### ISSUE TITLE
build error on examples

### ISSUE THREAD

**Issue by yan-ming** [RadeonOpenCompute/LLVM-AMDGPU-Assembler-Extra#8]
Hi @nhaustov,

It looks like some llvm internal changes will make it fail to build the examples on this line:

https://github.com/RadeonOpenCompute/LLVM-AMDGPU-Assembler-Extra/blob/master/examples/CMakeLists.txt#L79

Error messages:

```
error: unknown target triple 'amdgcn-amdhsa', please use -triple or -arch
make[2]: *** [examples/gfx8/s_memrealtime_inline.co] Error 1
make[1]: *** [examples/gfx8/CMakeFiles/s_memrealtime_inline_co.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by nhaustov** [comment]
Do you use latest Clang trunk?
Can you attach output of make VERBOSE=1?

Thanks

**Comment by yan-ming** [comment]
Hi @nhaustov, since there's no need to build AMDGPU-Assembler-Extra in LC now, so I think we can close this issue.

[1] https://github.com/RadeonOpenCompute/HCC-Native-GCN-ISA/wiki/Home/_compare/8e636f5fff566863cf86bdceccd81f2cfb2f9b6f...9fe8eb465093f83f9ffb8404037605b363a4f1c2
